import { Component } from '@angular/core';
import { IonicPage, NavController, NavParams } from 'ionic-angular';

@IonicPage()
@Component({
  selector: 'page-subcategorias',
  templateUrl: 'subcategorias.html',
})
export class SubcategoriasPage {

  public items: any[];

  public titleItem: any;

  constructor(public navCtrl: NavController, public navParams: NavParams) {

    this.titleItem = navParams.get('item_title');

  }




}


/*
 "Turismo & Hotéis":
      [
        "Hotéis",
        "Pontos Turísticos",
        "Pousadas",
        "Vans & Ônibus",
        "Rodoviárias",
        "Agência de Viagens",
        "Hotel Fazenda",
        "Motéis",
        "Resorts",
      ],
      "Alimentos & Bebidas":
      [
        "Churrascarias",
        "Doce e Salgados",
        "Fast Food e Lanches",
        "Pastelarias",
        "Pizzarias",
        "Produtos Naturais",
        "Restaurantes",
        "Sorveterias",
        "Vinhos e Adegas",
        "Espaço Vida Saudável",
        "Frios e Congelados",
        "Espetinhos",
        "Frigoríficos",
        "Cerealistas & Armazéns",
        "Conveniências",
        "Rodízios",
        "Choperias",
        "Comida Caseira",
        "Açougues",
        "Padarias",
        "Supermercados",
        "Distribuidoras",
        "Bebidas em Geral",
        "Hort Fruit",
        "Sacolão",
        "Peixarias",
        "Disk Bebida, Água e Gás",
        "Bares e Petiscos",
        "Chocolateira",
        "Iogurteria",
        "Cestas Café & Guloseimas",
      ],
      "Saúde & Bem Estar":
      [
        "Ambulâncias",
        "Laboratórios",
        "Massoterapia",
        "Oftalmologista",
        "Perfumaria e Cosméticos",
        "Salão de Beleza",
        "Produtos Naturais",
        "Colchões e Acessórios",
        "Posto de Saúde",
        "Personal Trainer",
        "Barbearias",
        "Manicure",
        "Homeopatia",
        "Funerárias",
        "Escolas Esportivas",
        "Médicos",
        "Academias",
        "Plano de Saúde",
        "Nutricionistas",
        "Clínicas Odontológicas",
        "Farmácias e Drogarias",
        "Cirurgias Estéticas",
        "Clínica Estética e SPA",
        "Hospitais e Clínicas",
        "Coaching",
        "Dança",
        "Purificadores de Água",
      ],
      "Disk Delivery":
      [
        "Pizzas",
        "Lanches",
        "Pastel",
        "Disk Entregas",
        "Gás e Água",
        "Gelo e Bebidas",
        "Delivery",
      ],
      "Construção & Decoração":
      [
        "Viveiro e Floriculturas",
        "Persianas e Cortinas",
        "Tintas",
        "Jardinagem",
        "Terraplanagens",
        "Telhas",
        "Serralherias",
        "Pré-moldados",
        "Piscinas",
        "Construtoras",
        "Fachadas",
        "Lavanderias",
        "Cama, Mesa e Banho",
        "Poço Artesiano",
        "Locação de Ferragens",
        "Proteção e Segurança",
        "Disk Entulhos",
        "Box e Esquadrias",
        "Aço e Ferros",
        "Pisos",
        "Guindaste e Munck",
        "Pedreiros e Pintores",
        "Equipamentos Eletrônicos",
        "Decoração",
        "Concretos",
        "Cerâmicas",
        "Calhas",
        "Calçadas",
        "Blocos Construção",
        "Engenheiros",
        "Arquitetura",
        "Vidraçarias",
        "Divisórias",
        "Mat. Elétricas & Instalações",
        "Material de Construção",
        "Marmoraria",
        "Marcenaria",
        "Madeireira",
        "Hidráulicas",
        "Gesso",
        "Estruturas Metálicas",
        "Esquadrias",
        "Eletricista",
        "Mineradoras",
      ],
      "Esporte & Lazer":
      [
        "Academia",
        "Clubes",
        "Barzinhos",
        "Espetinhos",
        "Pesqueiros",
        "Playgrounds",
        "Instrumentos Musicais",
        "Caça e Pesca",
        "Boliche",
        "Artes Marciais",
        "Festas e Eventos",
        "Motel",
        "Locadoras",
        "Teatros",
        "Materiais Esportivos",
        "Casas Noturnas",
        "Jogos",
        "Centros Esportivos",
        "Escola de Natação",
        "Cinemas",
        "Danceterias",
        "Games e Lan House",
      ],
      "Eventos & Festas":
      [
        "Tendas, Toldos e Coberturas",
        "Cestas Café da manhã",
        "Garçom",
        "Segurança",
        "Bolos e Doces",
        "Salgados",
        "Presentes",
        "Trajes",
        "Organização e Decoração",
        "Embalagens e Artigos para Festas",
        "Espaços para Eventos",
        "Eventos Corporativos",
        "DJ & Música ao vivo",
        "Buffet & Bebidas",
        "Aluguel de Equipamentos",
        "Promotores e Cerimoniais",
        "Carros & Limusines",
        "Iluminação & Sonorização",
        "Flores & Tele mensagens",
      ],
      "Moda & Estilo":
      [
        "Noivas",
        "Cabelo e Unhas",
        "Tecidos",
        "Calçados",
        "Uniformes",
        "Brinquedos",
        "Cosméticos",
        "Óticas & Acessórios",
        "Cama Mesa e Banho",
        "Aluguel de Roupas",
        "Presentes & Variedades",
        "Brechó",
        "Armarinhos",
        "Artesanato",
        "Acessórios & Afins",
        "Moda & Confecções",
        "Shopping"
      ],
      "Veículos":
      [
        "Peças",
        "Bicicletas",
        "Motocicletas",
        "Moto Peças",
        "Pneus e Rodas",
        "Carrocerias",
        "Borracharias e Recapadoras",
        "Despachantes – Auto Escolas",
        "Locação de Veículos",
        "Óleos e Lubrificantes",
        "Seguros",
        "Guinchos",
        "Chaveiros",
        "Lava jato",
        "Climatização & Refrigeração",
        "Lanternagem e Pintura",
        "Concessionárias – Revendas",
        "Auto Peças",
        "Combustíveis",
        "Consórcios",
        "Acessórios",
        "Mecânicas",
        "Retíficas",
        "Alinhamento & Balanceamento",
        "Radiadores",
        "Auto Elétricas",
        "Hidráulica",
        "Martelinho de Ouro",
        "Insufilme – Som – Alarme",
      ],
      "Informática & Escritório":
      [
        "Automação Comercial",
        "Automação Residencial",
        "Manutenção",
        "Suprimentos Informática",
        "Móveis & Equipamentos",
        "Celular e Telefonia",
        "Papelaria",
        "Gráficas",
        "Provedores de Internet",
        "Assistência Técnica",
        "Lan House",
        "Escolas de Informática",
        "Desenvolvedores de Site",
        "Web Designer",
      ],
      "Educação & Cultura":
      [
        "Aulas Particulares",
        "Banca de Revistas",
        "Materiais Escolares",
        "Cinema",
        "Treinamento",
        "Especializações",
        "Idiomas",
        "Ensino Superior",
        "Bibliotecas e Livrarias",
        "Escolas Públicas",
        "Escolas Particulares",
        "Cursos & Cursinhos",
        "Centro de Estudos",
        "Professores & Palestrantes",
      ],
      "Serviços & Profissionais":
      [
        "Imobiliária",
        "Refrigeração & Concertos",
        "Proteção & Segurança",
        "Marcenarias",
        "Desentupidoras",
        "Lavanderias",
        "Dedetizadoras",
        "Disk Entulho",
        "Extintores",
        "Guinchos",
        "Jardinagem",
        "Serralheria",
        "Poços Artesianos",
        "Cobranças",
        "Casas lotéricas",
        "Consórcios em Geral",
        "Arquitetos",
        "Eletricistas",
        "Engenharia",
        "Despachantes",
        "Borracharias",
        "Artesanatos",
        "Treinamentos & Coaching",
        "Cooperativas de Serviços",
        "Climatização",
        "Chaveiros",
        "Sindicatos",
        "Massagens",
        "Conserto de Roupas",
        "Eletrônicas",
        "Contabilidade",
        "Advocacias",
        "Correios",
        "Agências de Emprego",
        "Agência Bancárias",
        "Financeiras",
        "Delegacia",
        "Fórum e Tribunais",
        "Técnicos",
        "Representante Comercial",
        "Reciclagem",
        "Corretoras de Seguro",
        "Reformas e Serviços Gerais",
        "Terraplanagem",
        "Lava jatos",
        "Técnicos de Informática",
        "Cabelereiros",
        "Cartórios",
        "Assessorias & Consultorias",
      ],
      "Igrejas":
      [
        "Católica",
        "Evangélica",
        "Crente",
      ],
      "Móveis & Eletro":
      [
        "Antenas & Tv Assinaturas",
        "Eletromóveis",
        "Móveis e Eletrodomésticos",
        "Estofarias",
        "Móveis Planejados",
        "Colchões",
        "Eletro Portátil & UD",
      ],
      "Fretes & Transportes":
      [
        "Táxi",
        "Monitoramento",
        "Auto Munck & Guinchos",
        "Mudanças",
        "Moto taxi",
        "Aviação",
        "Turismos e Viagens",
        "Escolar",
        "Transportadoras",
        "Entregas Rápidas",
        "Fretes & Carretos",
        "Empilhadeira e Guindaste",
      ],
      "Mídia & Publicidade":
      [
        "Gráficas & Serigrafias",
        "Tele mensagens",
        "Rádio",
        "Cursos & Treinamentos",
        "Sites e Web Designer",
        "Jornais",
        "Carro de Som",
        "Brindes",
        "Comunicação Visual",
        "Publicidade & Web",
        "Sites de Notícias",
      ],
      "Indústrias e Ferragens":
      [
        "Elétrica Industrial",
        "Serviços Industriais",
        "Serralheria",
        "Refrigeração",
        "Metalúrgica",
        "Mecânica Industrial",
        "Máquinas e Equipamentos",
        "Indústrias",
        "Indústria Química",
        "Hidráulica",
        "Ferramentas e Ferragens",
        "Tornearia",
      ],
      "Variedade":
      [
      "Instrumentos Musicais",
      "Lotéricas",
      "Floriculturas & Orquidários",
      "Centro Comercial e Galerias",
      "Bolsas, Malas e Mochilas",
      "Bazar",
      "Aviamentos e Armarinhos",
      "Sex shop",
      "Pet Shop",
      "Purificadores e Filtro de Água",
      "Óticas"
      */